# Generated by Django 4.2.7 on 2023-12-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_add_vehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_vehicle",
            name="id",
        ),
        migrations.AlterField(
            model_name="add_vehicle",
            name="celermont_id",
            field=models.CharField(
                max_length=255,
                primary_key=True,
                serialize=False,
                verbose_name="Celermont ID",
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.add_vehicle",
                    ),
                ),
            ],
        ),
    ]
