# Generated by Django 4.2.7 on 2023-12-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_add_vehicle_id_alter_add_vehicle_celermont_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="vehicle",
        ),
    ]
